# See the documentation for more information:
# https://packit.dev/docs/configuration/

issue_repository: https://github.com/RelativeSure/fedora-copr-repo
copy_upstream_release_description: true
sync_changelog: true
#enable_net: true
preserve_project: true
srpm_build_deps: ["clang","cmake","cargo","rust","gcc","python3-devel","openssl-devel","perl-devel","openssl-perl","perl-FindBin","perl-IPC-Cmd"]

jobs:
- job: copr_build
  trigger: pull_request
  owner: relativesure
  project: general-repo
  targets:
    - fedora-stable
    - fedora-rawhide-x86_64
  actions:
    prepare-files: "make prepare"
    create-archive:
      - "make archive"
      - bash -c "ls -1 ./package-*.tar.gz"
    changelog-entry:
      - bash -c 'echo "- New release ${PACKIT_PROJECT_VERSION}"'

#- job: copr_build
#  trigger: commit
# branch: master
#  owner: relativesure
#  project: general-repo
#  targets:
 #   - fedora-41-x86_64
#    - fedora-rawhide-x86_64

packages:
  zellij:
    downstream_package_name: zellij
    upstream_package_name: zellij
    upstream_project_url: https://github.com/zellij-org/zellij
    paths:
      - ./zellij
    specfile_path: zellij.spec
    files_to_sync:
      - zellij.spec
  zenith:
    downstream_package_name: zenith
    upstream_package_name: zenith
    upstream_project_url: https://github.com/bvaisvil/zenith
    paths:
      - ./zenith
    specfile_path: zenith.spec
    files_to_sync:
      - zenith.spec
