# See the documentation for more information:
# https://packit.dev/docs/configuration/

issue_repository: https://github.com/RelativeSure/fedora-copr-repo

jobs:
- job: copr_build
  trigger: pull_request
  owner: relativesure
  project: general-repo
  targets:
    - fedora-41-x86_64
    - fedora-rawhide-x86_64
