# See the documentation for more information:
# https://packit.dev/docs/configuration/

issue_repository: https://github.com/RelativeSure/fedora-copr-repo

jobs:
- job: copr_build
  trigger: pull_request
  owner: relativesure
  project: general-repo
  targets:
    - fedora-41-x86_64
    - fedora-rawhide-x86_64

packages:
  zellij:
    downstream_package_name: zellij
    upstream_package_name: zellij
    upstream_project_url: https://github.com/zellij-org/zellij
    paths:
      - ./zellij
    specfile_path: zellij.spec
    files_to_sync:
      - zellij.spec
      - zellij/zellij.spec
      - .packit.yaml
  zenith:
    downstream_package_name: zenith
    upstream_package_name: zenith
    upstream_project_url: https://github.com/bvaisvil/zenith
    paths:
      - ./zenith
    specfile_path: zenith.spec
    files_to_sync:
      - zenith.spec
      - zenith/zenith.spec
      - .packit.yaml
